name:                lsp-test-notebook
version:             0.1.0.0
license:             MIT
author:              "Tom McLaughlin"
maintainer:          "Tom McLaughlin"
copyright:           "2026 Tom McLaughlin"
synopsis:            "LSP testing utilities for notebook-style language servers"
description:         "A library providing utilities for end-to-end testing of LSP language servers, with special support for notebook-style code transformations."

extra-source-files:
- README.md

default-extensions:
- OverloadedStrings
- QuasiQuotes
- NamedFieldPuns
- RecordWildCards
- ScopedTypeVariables
- FlexibleContexts
- FlexibleInstances
- LambdaCase
- ViewPatterns
- MultiWayIf
- TupleSections
- NumericUnderscores
- TypeApplications
- GeneralizedNewtypeDeriving
- DataKinds
- TypeOperators
- ConstraintKinds

ghc-options:
- -Wall
- -Wunused-packages
- -fno-warn-name-shadowing

dependencies:
- base >= 4.7 && < 5
- lsp-test >= 0.15
- lsp-types >= 2.0
- aeson
- text
- bytestring
- containers
- directory
- filepath
- temporary
- process
- async
- unliftio
- unliftio-core
- exceptions
- mtl
- monad-control
- monad-logger
- sandwich >= 0.1
- lens
- data-default
- string-interpolate

library:
  source-dirs: src
  exposed-modules:
  - Language.LSP.Test.Notebook
