name:                lsp-test-helpers
version:             0.1.0.0
license:             MIT
author:              "Tom McLaughlin"
maintainer:          "Tom McLaughlin"
copyright:           "2026 Tom McLaughlin"
synopsis:            "LSP testing utilities for notebook-style language servers"
description:         "A library providing utilities for end-to-end testing of LSP language servers, with special support for notebook-style code transformations."

extra-source-files:
- README.md

default-extensions:
- OverloadedStrings
- QuasiQuotes
- NamedFieldPuns
- RecordWildCards
- ScopedTypeVariables
- FlexibleContexts
- FlexibleInstances
- LambdaCase
- ViewPatterns
- MultiWayIf
- TupleSections
- NumericUnderscores
- TypeApplications
- GeneralizedNewtypeDeriving
- DataKinds
- TypeOperators
- ConstraintKinds

ghc-options:
- -Wall
- -Wunused-packages
- -fno-warn-name-shadowing

dependencies:
- aeson
- base >= 4.7 && < 5
- bytestring
- containers
- data-default
- exceptions
- filepath
- lens
- lsp-test >= 0.15
- lsp-types >= 2.0
- monad-logger
- sandwich >= 0.1
- string-interpolate
- temporary
- text
- unliftio
- unliftio-core

library:
  source-dirs: src
  exposed-modules:
  - Language.LSP.Test.Helpers
