resolver: nightly-2025-12-22

packages:
- .

nix:
  enable: false

system-ghc: true

extra-deps:
- git: https://github.com/codedownio/sandwich
  # long-running-nodes branch
  commit: c3e16ccda384917fba1ccc5f3cf8f592415562c1
  subdirs:
  - sandwich
  - sandwich-contexts
  - sandwich-quickcheck

- git: https://github.com/codedownio/lsp.git
  # upgrade-monads-newest-jan2026 branch
  commit: d920b28aa25d454812d8d9bbd922e893574d45bc
  subdirs:
  - lsp
  - lsp-test
  - lsp-types

- sorted-list-0.2.3.1@sha256:643700d012bffa4aff8371ace31c3b6aea6e7e894c185ef52337f8faf9f18f8d,2336
